// <auto-generated />
using LearningDotNetCoreMVC.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearningDotNetCoreMVC.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260406181141_SeedingProducts")]
    partial class SeedingProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearningDotNetCoreMVC.Models.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            ID = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            ID = 3,
                            DisplayOrder = 3,
                            Name = "SelfHelp"
                        });
                });

            modelBuilder.Entity("LearningDotNetCoreMVC.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("PriceForFifty")
                        .HasColumnType("double precision");

                    b.Property<double>("PriceForHundred")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Paulo Coelho",
                            Description = "A journey of self-discovery",
                            ISBN = "ISBN001",
                            Name = "The Alchemist",
                            Price = 499.0,
                            PriceForFifty = 450.0,
                            PriceForHundred = 400.0
                        },
                        new
                        {
                            Id = 2,
                            Author = "Robert C. Martin",
                            Description = "A handbook of agile software craftsmanship",
                            ISBN = "ISBN002",
                            Name = "Clean Code",
                            Price = 999.0,
                            PriceForFifty = 900.0,
                            PriceForHundred = 850.0
                        },
                        new
                        {
                            Id = 3,
                            Author = "Andrew Hunt",
                            Description = "Your journey to mastery",
                            ISBN = "ISBN003",
                            Name = "The Pragmatic Programmer",
                            Price = 899.0,
                            PriceForFifty = 800.0,
                            PriceForHundred = 750.0
                        },
                        new
                        {
                            Id = 4,
                            Author = "James Clear",
                            Description = "An easy & proven way to build good habits",
                            ISBN = "ISBN004",
                            Name = "Atomic Habits",
                            Price = 699.0,
                            PriceForFifty = 650.0,
                            PriceForHundred = 600.0
                        },
                        new
                        {
                            Id = 5,
                            Author = "Cal Newport",
                            Description = "Rules for focused success",
                            ISBN = "ISBN005",
                            Name = "Deep Work",
                            Price = 799.0,
                            PriceForFifty = 720.0,
                            PriceForHundred = 680.0
                        },
                        new
                        {
                            Id = 6,
                            Author = "Robert Kiyosaki",
                            Description = "What the rich teach their kids",
                            ISBN = "ISBN006",
                            Name = "Rich Dad Poor Dad",
                            Price = 599.0,
                            PriceForFifty = 550.0,
                            PriceForHundred = 500.0
                        },
                        new
                        {
                            Id = 7,
                            Author = "Peter Thiel",
                            Description = "Notes on startups and building the future",
                            ISBN = "ISBN007",
                            Name = "Zero to One",
                            Price = 749.0,
                            PriceForFifty = 700.0,
                            PriceForHundred = 650.0
                        },
                        new
                        {
                            Id = 8,
                            Author = "Napoleon Hill",
                            Description = "Classic personal success guide",
                            ISBN = "ISBN008",
                            Name = "Think and Grow Rich",
                            Price = 399.0,
                            PriceForFifty = 350.0,
                            PriceForHundred = 300.0
                        },
                        new
                        {
                            Id = 9,
                            Author = "Yuval Noah Harari",
                            Description = "A brief history of humankind",
                            ISBN = "ISBN009",
                            Name = "Sapiens",
                            Price = 1099.0,
                            PriceForFifty = 1000.0,
                            PriceForHundred = 950.0
                        },
                        new
                        {
                            Id = 10,
                            Author = "Eric Ries",
                            Description = "How today's entrepreneurs use continuous innovation",
                            ISBN = "ISBN010",
                            Name = "The Lean Startup",
                            Price = 899.0,
                            PriceForFifty = 820.0,
                            PriceForHundred = 780.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
